### ISSUE TITLE
Prepare plugin "assets"

### ISSUE THREAD

**Issue by ReinhardG** [bitmovin/bitmovinvideo-wordpress#15]
Prepare content, like text, screenshots, etc. as stated at https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/

**Comment by ReinhardG** [comment]
Screenshots do not appear on plugin page (https://wordpress.org/plugins/bitmovin-video/screenshots/)

**Comment by tristoboydo** [comment]
They are named wrong. I have uploaded new images. Should be OK when we push the Assets folder up to the Wordpress plugin repository.
